baseURL = "https://raphazilla.github.io/raphazilla/"
languageCode = "en-us"
title = "Raphazilla"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "Rapha Prosillo - All rights reserved"
enableEmoji = true
publishDir = "content"
disqusShortname = "raphazilla"
googleAnalytics = "G-6SVRZ2T5RW"

[params]
  logo = "/raphazilla/images/logo2.jpg"
  description ="Another Techblog.."

[params.author]
  name = "Rapha"
  thumbnail = "/raphazilla/images/author.jpg"
  description = "Lifelong Learner, Senior System Administrator, Cloud and DevOps enthusiastic, IaC advocate and Gardener"

[params.index]
  picture = "/raphazilla/images/author.jpg"
  title = "Rapha here!ğŸ˜"
  subtitle = "Brazilian guys living in the amazing Czech Republic!"
  mdtext = '''
ğŸ‘‹ OlÃ¡ pessoal!
Sou o Rapha , um Administrador de Sistemas SÃªnior com mais de 15 anos de experiÃªncia, especializado em ResiliÃªncia e Backup e RecuperaÃ§Ã£o de Dados. Tenho experiÃªncia em gerenciar sistemas crÃ­ticos e garantir a seguranÃ§a de cargas de trabalho diversas. ğŸ›¡ï¸ğŸ’»
Ao longo da minha carreira, tive o privilÃ©gio de contribuir com minhas habilidades para grandes empresas de tecnologia, oferecendo suporte a diversas indÃºstrias, incluindo os setores farmacÃªutico e quÃ­mico. ğŸ­
Com uma curiosidade natural, estou sempre em busca de algo novo para aprender. Seja as Ãºltimas tecnologias, explorar arte e mÃºsica, mergulhar na histÃ³ria ou imergir nas maravilhas da natureza, sou apaixonado por expandir meu conhecimento e habilidades. 
ğŸŒŸ Vamos nos conectar e explorar o emocionante mundo da tecnologia e alÃ©m! ğŸš€
'''
  alertbar = true

[params.social]
  github = "raphazilla"
  linkedin = "raphaelprosillo"
  twitter = "ollisorp"

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 200
    url = "/"

[[redirects]]
  from = '/**'
  status = 404
  to = '/404.html'