baseURL = "https://prosillo.github.io/raphazilla/"
languageCode = "en-us"
title = "Raphazilla"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "Rapha Prosillo - All rights reserved"
enableEmoji = true
publishDir = "content"

[params]
  logo = "/raphazilla/images/logo.png"
  description ="the clean blog!"
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  name = "Rapha"
  thumbnail = "/raphazilla/images/author.jpg"
  description = "Creator of this blog."

[params.index]
  picture = "/raphazilla/images/author.jpg"
  title = "Rapha here!"
  subtitle = "Brazilian guys living in the amazing Czech Republic!"
  mdtext = '''
ğŸ‘‹ Hi there! I'm a Senior System Administrator with over 15 years of experience, specializing in Resilience and Data Backup and Recovery. I thrive in managing mission-critical systems and securing diverse workloads. ğŸ›¡ï¸ğŸ’»

I've had the privilege of contributing my skills to Big Tech companies, offering support to various industries, including Pharma and Chemical sectors. ğŸ­

Being naturally curious, I'm always on the lookout for something new to learn. Whether it's the latest technologies, exploring art and music, delving into history, or immersing myself in the wonders of nature, I'm passionate about expanding my knowledge and skills. ğŸŒŸ Let's connect and explore the exciting world of technology and beyond! ğŸš€
'''
  alertbar = true

[params.social]
  github = "prosillo"
  linkedin = "raphaelprosillo"

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "Separate"
    weight = 100
    identifier = "separate"
    url = "/separate"
[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 200
    url = "/"
[[menu.main]]
    name = "Imprint"
    identifier = "imprint"
    weight = 200
    url = "/static/imprint"